# Generated by Django 5.1.2 on 2024-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('cake_flavour', models.CharField(max_length=100)),
            ],
        ),
    ]
