# Generated by Django 5.1.2 on 2024-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake_order',
            name='cake_flavour',
            field=models.CharField(choices=[(1, 'Chocolate'), (2, 'Strawberry'), (3, 'Vanilla')], default='Vanilla', max_length=100),
        ),
    ]
