# Generated by Django 5.1.2 on 2024-10-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_cake_order_cake_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('customer_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.cake_order')),
            ],
        ),
    ]
